"""ps

Revision ID: 537547987ae9
Revises: f4b53dde4c06
Create Date: 2018-07-16 23:44:50.913299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537547987ae9'
down_revision = 'f4b53dde4c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
