"""empty message

Revision ID: 7f7c4a12a22a
Revises: 3cba60b0d3f4
Create Date: 2018-07-01 16:20:58.871074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7c4a12a22a'
down_revision = '3cba60b0d3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('paused', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('status_list', sa.String(), nullable=True))
    op.drop_column('tasks', 'puased')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('puased', sa.VARCHAR(), nullable=True))
    op.drop_column('tasks', 'status_list')
    op.drop_column('tasks', 'paused')
    # ### end Alembic commands ###
